name: Deploy docs
on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Checkout
        uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build
        env:
          TURBO_TOKEN: RGLUn21VCrni7UZjOhuM0y29
          TURBO_TEAM: hugos-projects-6ecc346d
      - name: Deploy storybook
        working-directory: ./packages/docs
        run: touch storybook-static/.nojekyll && npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}