name: Deploy docs 

on: 
  push: 
    branches: 
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
      - run: actions/checkout@v4

      - name: Setup Node.js
      - run: actions/setup-node@v4
        with:
          node-version: 18

      - name: npm ci
      - run: npm run build

      - name: Deploy Storybook
        working-directory: ./packages/docs
      - run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env: 
            GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}